export const states = [
  {
    id: "AL",
    name: "Alabama",
    capital: "Montgomery",
    bird: "Yellowhammer",
    slogan: "Sweet Home Alabama",
    population: 4903185,
    nickname: "The Yellowhammer State",
    totalArea: 52420,
  },
  {
    id: "AK",
    name: "Alaska",
    capital: "Juneau",
    bird: "Willow Ptarmigan",
    slogan: "North to the Future",
    population: 731545,
    nickname: "The Last Frontier",
    totalArea: 665384,
  },
  {
    id: "AZ",
    name: "Arizona",
    capital: "Phoenix",
    bird: "Cactus Wren",
    slogan: "The Grand Canyon State",
    population: 7278717,
    nickname: "The Grand Canyon State",
    totalArea: 113990,
  },
  {
    id: "AR",
    name: "Arkansas",
    capital: "Little Rock",
    bird: "Northern Mockingbird",
    slogan: "The Natural State",
    population: 3017804,
    nickname: "The Natural State",
    totalArea: 53179,
  },
  {
    id: "CA",
    name: "California",
    capital: "Sacramento",
    bird: "California Quail",
    slogan: "Eureka",
    population: 39512223,
    nickname: "The Golden State",
    totalArea: 163695,
  },
  {
    id: "CO",
    name: "Colorado",
    capital: "Denver",
    bird: "Lark Bunting",
    slogan: "Colorful Colorado",
    population: 5758736,
    nickname: "The Centennial State",
    totalArea: 104094,
  },
  {
    id: "CT",
    name: "Connecticut",
    capital: "Hartford",
    bird: "American Robin",
    slogan: "Constitution State",
    population: 3565287,
    nickname: "The Constitution State",
    totalArea: 5543,
  },
  {
    id: "DE",
    name: "Delaware",
    capital: "Dover",
    bird: "Delaware Blue Hen",
    slogan: "Liberty and Independence",
    population: 973764,
    nickname: "The First State",
    totalArea: 2489,
  },
  {
    id: "FL",
    name: "Florida",
    capital: "Tallahassee",
    bird: "Northern Mockingbird",
    slogan: "In God We Trust",
    population: 21477737,
    nickname: "The Sunshine State",
    totalArea: 65758,
  },
  {
    id: "GA",
    name: "Georgia",
    capital: "Atlanta",
    bird: "Brown Thrasher",
    slogan: "Wisdom, Justice, Moderation",
    population: 10617423,
    nickname: "The Peach State",
    totalArea: 59425,
  },
  {
    id: "HI",
    name: "Hawaii",
    capital: "Honolulu",
    bird: "Nene",
    slogan: "Ua Mau ke Ea o ka ʻĀina i ka Pono",
    population: 1415872,
    nickname: "The Aloha State",
    totalArea: 10931,
  },
  {
    id: "ID",
    name: "Idaho",
    capital: "Boise",
    bird: "Mountain Bluebird",
    slogan: "Esto Perpetua",
    population: 1787065,
    nickname: "The Gem State",
    totalArea: 83569,
  },
  {
    id: "IL",
    name: "Illinois",
    capital: "Springfield",
    bird: "Northern Cardinal",
    slogan: "State Sovereignty, National Union",
    population: 12671821,
    nickname: "The Prairie State",
    totalArea: 57914,
  },
  {
    id: "IN",
    name: "Indiana",
    capital: "Indianapolis",
    bird: "Northern Cardinal",
    slogan: "The Crossroads of America",
    population: 6732219,
    nickname: "The Hoosier State",
    totalArea: 36420,
  },
  {
    id: "IA",
    name: "Iowa",
    capital: "Des Moines",
    bird: "Eastern Goldfinch",
    slogan: "Our Liberties We Prize and Our Rights We Will Maintain",
    population: 3155070,
    nickname: "The Hawkeye State",
    totalArea: 56273,
  },
  {
    id: "KS",
    name: "Kansas",
    capital: "Topeka",
    bird: "Western Meadowlark",
    slogan: "Ad astra per aspera",
    population: 2913314,
    nickname: "The Sunflower State",
    totalArea: 82278,
  },
  {
    id: "KY",
    name: "Kentucky",
    capital: "Frankfort",
    bird: "Northern Cardinal",
    slogan: "United we stand, divided we fall",
    population: 4467673,
    nickname: "The Bluegrass State",
    totalArea: 40408,
  },
  {
    id: "LA",
    name: "Louisiana",
    capital: "Baton Rouge",
    bird: "Brown Pelican",
    slogan: "Union, Justice, Confidence",
    population: 4648794,
    nickname: "The Pelican State",
    totalArea: 52378,
  },
  {
    id: "ME",
    name: "Maine",
    capital: "Augusta",
    bird: "Chickadee",
    slogan: "Dirigo",
    population: 1344212,
    nickname: "The Pine Tree State",
    totalArea: 35380,
  },
  {
    id: "MD",
    name: "Maryland",
    capital: "Annapolis",
    bird: "Baltimore Oriole",
    slogan: "Fatti maschii, parole femine",
    population: 6045680,
    nickname: "The Old Line State",
    totalArea: 12407,
  },
  {
    id: "MA",
    name: "Massachusetts",
    capital: "Boston",
    bird: "Black-Capped Chickadee",
    slogan: "Ense petit placidam sub libertate quietem",
    population: 6892503,
    nickname: "The Bay State",
    totalArea: 10554,
  },
  {
    id: "MI",
    name: "Michigan",
    capital: "Lansing",
    bird: "American Robin",
    slogan: "Si quaeris peninsulam amoenam circumspice",
    population: 9986857,
    nickname: "The Great Lakes State",
    totalArea: 96714,
  },
  {
    id: "MN",
    name: "Minnesota",
    capital: "Saint Paul",
    bird: "Common Loon",
    slogan: `L'Étoile du Nord`,
    population: 5639632,
    nickname: "The North Star State",
    totalArea: 86936,
  },
  {
    id: "MS",
    name: "Mississippi",
    capital: "Jackson",
    bird: "Northern Mockingbird",
    slogan: "Virtute et armis",
    population: 2976149,
    nickname: "The Magnolia State",
    totalArea: 48432,
  },
  {
    id: "MO",
    name: "Missouri",
    capital: "Jefferson City",
    bird: "Eastern Bluebird",
    slogan: "Salus populi suprema lex esto",
    population: 6137428,
    nickname: "The Show Me State",
    totalArea: 69707,
  },
  {
    id: "MT",
    name: "Montana",
    capital: "Helena",
    bird: "Western Meadowlark",
    slogan: "Oro y plata",
    population: 1068778,
    nickname: "The Treasure State",
    totalArea: 147040,
  },
  {
    id: "NE",
    name: "Nebraska",
    capital: "Lincoln",
    bird: "Western Meadowlark",
    slogan: "Equality Before the Law",
    population: 1934408,
    nickname: "The Cornhusker State",
    totalArea: 77348,
  },
  {
    id: "NV",
    name: "Nevada",
    capital: "Carson City",
    bird: "Mountain Bluebird",
    slogan: "All For Our Country",
    population: 3080156,
    nickname: "The Silver State",
    totalArea: 110572,
  },
  {
    id: "NH",
    name: "New Hampshire",
    capital: "Concord",
    bird: "Purple Finch",
    slogan: "Live Free or Die",
    population: 1359711,
    nickname: "The Granite State",
    totalArea: 9349,
  },
  {
    id: "NJ",
    name: "New Jersey",
    capital: "Trenton",
    bird: "Eastern Goldfinch",
    slogan: "Liberty and Prosperity",
    population: 8882190,
    nickname: "The Garden State",
    totalArea: 8723,
  },
  {
    id: "NM",
    name: "New Mexico",
    capital: "Santa Fe",
    bird: "Greater Roadrunner",
    slogan: "Crescit Eundo",
    population: 2096829,
    nickname: "The Land of Enchantment",
    totalArea: 121590,
  },
  {
    id: "NY",
    name: "New York",
    capital: "Albany",
    bird: "Eastern Bluebird",
    slogan: "Excelsior",
    population: 19453561,
    nickname: "The Empire State",
    totalArea: 54555,
  },
  {
    id: "NC",
    name: "North Carolina",
    capital: "Raleigh",
    bird: "Northern Cardinal",
    slogan: "Esse quam videri",
    population: 10488084,
    nickname: "The Tar Heel State",
    totalArea: 53819,
  },
  {
    id: "ND",
    name: "North Dakota",
    capital: "Bismarck",
    bird: "Western Meadowlark",
    slogan: "Liberty and Union, Now and Forever, One and Inseparable",
    population: 762062,
    nickname: "The Peace Garden State",
    totalArea: 70698,
  },
  {
    id: "OH",
    name: "Ohio",
    capital: "Columbus",
    bird: "Northern Cardinal",
    slogan: "With God, All Things Are Possible",
    population: 11689100,
    nickname: "The Buckeye State",
    totalArea: 44826,
  },
  {
    id: "OK",
    name: "Oklahoma",
    capital: "Oklahoma City",
    bird: "Scissor-tailed Flycatcher",
    slogan: "Labor Omnia Vincit",
    population: 3956971,
    nickname: "The Sooner State",
    totalArea: 69899,
  },
  {
    id: "OR",
    name: "Oregon",
    capital: "Salem",
    bird: "Western Meadowlark",
    slogan: "Alis Volat Propriis",
    population: 4217737,
    nickname: "The Beaver State",
    totalArea: 98379,
  },
  {
    id: "PA",
    name: "Pennsylvania",
    capital: "Harrisburg",
    bird: "Ruffed Grouse",
    slogan: "Virtue, Liberty, and Independence",
    population: 12801989,
    nickname: "The Keystone State",
    totalArea: 46054,
  },
  {
    id: "RI",
    name: "Rhode Island",
    capital: "Providence",
    bird: "Rhode Island Red",
    slogan: "Hope",
    population: 1059361,
    nickname: "The Ocean State",
    totalArea: 1545,
  },
  {
    id: "SC",
    name: "South Carolina",
    capital: "Columbia",
    bird: "Carolina Wren",
    slogan: "Dum Spiro Spero",
    population: 5148714,
    nickname: "The Palmetto State",
    totalArea: 32020,
  },
  {
    id: "SD",
    name: "South Dakota",
    capital: "Pierre",
    bird: "Ring-necked Pheasant",
    slogan: "Under God the People Rule",
    population: 884659,
    nickname: "The Mount Rushmore State",
    totalArea: 77116,
  },
  {
    id: "TN",
    name: "Tennessee",
    capital: "Nashville",
    bird: "Northern Mockingbird",
    slogan: "Agriculture and Commerce",
    population: 6829174,
    nickname: "The Volunteer State",
    totalArea: 42144,
  },
  {
    id: "TX",
    name: "Texas",
    capital: "Austin",
    bird: "Northern Mockingbird",
    slogan: "Friendship",
    population: 28995881,
    nickname: "The Lone Star State",
    totalArea: 268596,
  },
  {
    id: "UT",
    name: "Utah",
    capital: "Salt Lake City",
    bird: "California Gull",
    slogan: "Industry",
    population: 3205958,
    nickname: "The Beehive State",
    totalArea: 84897,
  },
  {
    id: "VT",
    name: "Vermont",
    capital: "Montpelier",
    bird: "Hermit Thrush",
    slogan: "Freedom and Unity",
    population: 623989,
    nickname: "The Green Mountain State",
    totalArea: 9616,
  },
  {
    id: "VA",
    name: "Virginia",
    capital: "Richmond",
    bird: "Northern Cardinal",
    slogan: "Sic Semper Tyrannis",
    population: 8535519,
    nickname: "The Old Dominion State",
    totalArea: 42775,
  },
  {
    id: "WA",
    name: "Washington",
    capital: "Olympia",
    bird: "Willow Goldfinch",
    slogan: "Al-ki",
    population: 7614893,
    nickname: "The Evergreen State",
    totalArea: 71298,
  },
  {
    id: "WV",
    name: "West Virginia",
    capital: "Charleston",
    bird: "Northern Cardinal",
    slogan: "Montani Semper Liberi",
    population: 1792147,
    nickname: "The Mountain State",
    totalArea: 24230,
  },
  {
    id: "WI",
    name: "Wisconsin",
    capital: "Madison",
    bird: "American Robin",
    slogan: "Forward",
    population: 5822434,
    nickname: "The Badger State",
    totalArea: 65496,
  },
  {
    id: "WY",
    name: "Wyoming",
    capital: "Cheyenne",
    bird: "Western Meadowlark",
    slogan: "Equal Rights",
    population: 578759,
    nickname: "The Equality State",
    totalArea: 97813,
  },
];
