import { State } from "./definitions";

export const states: State[] = [
  {
    id: "AL",
    name: "Alabama",
    capital: "Montgomery",
    bird: "Yellowhammer",
    slogan: "Sweet Home Alabama",
    population: "4,903,185",
    nickname: "The Yellowhammer State",
    totalArea: "52,420",
    imageSrc: "/images/flags/al.svg",
    statehoodDate: new Date("1819-12-14"),
  },
  {
    id: "AK",
    name: "Alaska",
    capital: "Juneau",
    bird: "Willow Ptarmigan",
    slogan: "North to the Future",
    population: "731,545",
    nickname: "The Last Frontier",
    totalArea: "665,384",
    imageSrc: "/images/flags/ak.svg",
    statehoodDate: new Date("1959-01-03"),
  },
  {
    id: "AZ",
    name: "Arizona",
    capital: "Phoenix",
    bird: "Cactus Wren",
    slogan: "The Grand Canyon State",
    population: "7,278,717",
    nickname: "The Grand Canyon State",
    totalArea: "113,990",
    imageSrc: "/images/flags/az.svg",
    statehoodDate: new Date("1912-02-14"),
  },
  {
    id: "AR",
    name: "Arkansas",
    capital: "Little Rock",
    bird: "Northern Mockingbird",
    slogan: "The Natural State",
    population: "3,017,804",
    nickname: "The Natural State",
    totalArea: "53,179",
    imageSrc: "/images/flags/ar.svg",
    statehoodDate: new Date("1836-06-15"),
  },
  {
    id: "CA",
    name: "California",
    capital: "Sacramento",
    bird: "California Quail",
    slogan: "Eureka",
    population: "39,512,223",
    nickname: "The Golden State",
    totalArea: "163,695",
    imageSrc: "/images/flags/ca.svg",
    statehoodDate: new Date("1850-09-09"),
  },
  {
    id: "CO",
    name: "Colorado",
    capital: "Denver",
    bird: "Lark Bunting",
    slogan: "Colorful Colorado",
    population: "5,758,736",
    nickname: "The Centennial State",
    totalArea: "104,094",
    imageSrc: "/images/flags/co.svg",
    statehoodDate: new Date("1876-08-01"),
  },
  {
    id: "CT",
    name: "Connecticut",
    capital: "Hartford",
    bird: "American Robin",
    slogan: "Constitution State",
    population: "3,565,287",
    nickname: "The Constitution State",
    totalArea: "5,543",
    imageSrc: "/images/flags/ct.svg",
    statehoodDate: new Date("1788-01-09"),
  },
  {
    id: "DE",
    name: "Delaware",
    capital: "Dover",
    bird: "Delaware Blue Hen",
    slogan: "Liberty and Independence",
    population: "973,764",
    nickname: "The First State",
    totalArea: "2,489",
    imageSrc: "/images/flags/de.svg",
    statehoodDate: new Date("1787-12-07"),
  },
  {
    id: "FL",
    name: "Florida",
    capital: "Tallahassee",
    bird: "Northern Mockingbird",
    slogan: "In God We Trust",
    population: "21,477,737",
    nickname: "The Sunshine State",
    totalArea: "65,758",
    imageSrc: "/images/flags/fl.svg",
    statehoodDate: new Date("1845-03-03"),
  },
  {
    id: "GA",
    name: "Georgia",
    capital: "Atlanta",
    bird: "Brown Thrasher",
    slogan: "Wisdom, Justice, Moderation",
    population: "10,617,423",
    nickname: "The Peach State",
    totalArea: "59,425",
    imageSrc: "/images/flags/ga.svg",
    statehoodDate: new Date("1788-01-02"),
  },
  {
    id: "HI",
    name: "Hawaii",
    capital: "Honolulu",
    bird: "Nene",
    slogan: "Ua Mau ke Ea o ka ʻĀina i ka Pono",
    population: "1,415,872",
    nickname: "The Aloha State",
    totalArea: "10,931",
    imageSrc: "/images/flags/hi.svg",
    statehoodDate: new Date("1959-08-21"),
  },
  {
    id: "ID",
    name: "Idaho",
    capital: "Boise",
    bird: "Mountain Bluebird",
    slogan: "Esto Perpetua",
    population: "1,787,065",
    nickname: "The Gem State",
    totalArea: "83,569",
    imageSrc: "/images/flags/id.jpg",
    statehoodDate: new Date("1890-07-03"),
  },
  {
    id: "IL",
    name: "Illinois",
    capital: "Springfield",
    bird: "Northern Cardinal",
    slogan: "State Sovereignty, National Union",
    population: "12,671,821",
    nickname: "The Prairie State",
    totalArea: "57,914",
    imageSrc: "/images/flags/il.svg",
    statehoodDate: new Date("1818-12-03"),
  },
  {
    id: "IN",
    name: "Indiana",
    capital: "Indianapolis",
    bird: "Northern Cardinal",
    slogan: "The Crossroads of America",
    population: "6,732,219",
    nickname: "The Hoosier State",
    totalArea: "36,420",
    imageSrc: "/images/flags/in.svg",
    statehoodDate: new Date("1816-12-11"),
  },
  {
    id: "IA",
    name: "Iowa",
    capital: "Des Moines",
    bird: "Eastern Goldfinch",
    slogan: "Our Liberties We Prize and Our Rights We Will Maintain",
    population: "3,155,070",
    nickname: "The Hawkeye State",
    totalArea: "56,273",
    imageSrc: "/images/flags/ia.svg",
    statehoodDate: new Date("1846-12-28"),
  },
  {
    id: "KS",
    name: "Kansas",
    capital: "Topeka",
    bird: "Western Meadowlark",
    slogan: "Ad astra per aspera",
    population: "2,913,314",
    nickname: "The Sunflower State",
    totalArea: "82,278",
    imageSrc: "/images/flags/ks.jpg",
    statehoodDate: new Date("1861-01-29"),
  },
  {
    id: "KY",
    name: "Kentucky",
    capital: "Frankfort",
    bird: "Northern Cardinal",
    slogan: "United we stand, divided we fall",
    population: "4,467,673",
    nickname: "The Bluegrass State",
    totalArea: "40,408",
    imageSrc: "/images/flags/ky.jpg",
    statehoodDate: new Date("1792-06-01"),
  },
  {
    id: "LA",
    name: "Louisiana",
    capital: "Baton Rouge",
    bird: "Brown Pelican",
    slogan: "Union, Justice, Confidence",
    population: "4,648,794",
    nickname: "The Pelican State",
    totalArea: "52,378",
    imageSrc: "/images/flags/la.jpg",
    statehoodDate: new Date("1812-04-30"),
  },
  {
    id: "ME",
    name: "Maine",
    capital: "Augusta",
    bird: "Chickadee",
    slogan: "Dirigo",
    population: "1,344,212",
    nickname: "The Pine Tree State",
    totalArea: "35,380",
    imageSrc: "/images/flags/me.jpg",
    statehoodDate: new Date("1820-03-15"),
  },
  {
    id: "MD",
    name: "Maryland",
    capital: "Annapolis",
    bird: "Baltimore Oriole",
    slogan: "Fatti maschii, parole femine",
    population: "6,045,680",
    nickname: "The Old Line State",
    totalArea: "12,407",
    imageSrc: "/images/flags/md.svg",
    statehoodDate: new Date("1788-04-28"),
  },
  {
    id: "MA",
    name: "Massachusetts",
    capital: "Boston",
    bird: "Black-Capped Chickadee",
    slogan: "Ense petit placidam sub libertate quietem",
    population: "6,892,503",
    nickname: "The Bay State",
    totalArea: "10,554",
    imageSrc: "/images/flags/ma.jpg",
    statehoodDate: new Date("1788-02-06"),
  },
  {
    id: "MI",
    name: "Michigan",
    capital: "Lansing",
    bird: "American Robin",
    slogan: "Si quaeris peninsulam amoenam circumspice",
    population: "9,986,857",
    nickname: "The Great Lakes State",
    totalArea: "96,714",
    imageSrc: "/images/flags/mi.svg",
    statehoodDate: new Date("1837-01-26"),
  },
  {
    id: "MN",
    name: "Minnesota",
    capital: "Saint Paul",
    bird: "Common Loon",
    slogan: `L'Étoile du Nord`,
    population: "5,639,632",
    nickname: "The North Star State",
    totalArea: "86,936",
    imageSrc: "/images/flags/mn.svg",
    statehoodDate: new Date("1858-05-11"),
  },
  {
    id: "MS",
    name: "Mississippi",
    capital: "Jackson",
    bird: "Northern Mockingbird",
    slogan: "Virtute et armis",
    population: "2,976,149",
    nickname: "The Magnolia State",
    totalArea: "48,432",
    imageSrc: "/images/flags/ms.svg",
    statehoodDate: new Date("1817-12-10"),
  },
  {
    id: "MO",
    name: "Missouri",
    capital: "Jefferson City",
    bird: "Eastern Bluebird",
    slogan: "Salus populi suprema lex esto",
    population: "6,137,428",
    nickname: "The Show Me State",
    totalArea: "69,707",
    imageSrc: "/images/flags/mo.svg",
    statehoodDate: new Date("1821-08-10"),
  },
  {
    id: "MT",
    name: "Montana",
    capital: "Helena",
    bird: "Western Meadowlark",
    slogan: "Oro y plata",
    population: "1,068,778",
    nickname: "The Treasure State",
    totalArea: "147,040",
    imageSrc: "/images/flags/mt.jpg",
    statehoodDate: new Date("1889-11-08"),
  },
  {
    id: "NE",
    name: "Nebraska",
    capital: "Lincoln",
    bird: "Western Meadowlark",
    slogan: "Equality Before the Law",
    population: "1,934,408",
    nickname: "The Cornhusker State",
    totalArea: "77,348",
    imageSrc: "/images/flags/ne.svg",
    statehoodDate: new Date("1867-03-01"),
  },
  {
    id: "NV",
    name: "Nevada",
    capital: "Carson City",
    bird: "Mountain Bluebird",
    slogan: "All For Our Country",
    population: "3,080,156",
    nickname: "The Silver State",
    totalArea: "110,572",
    imageSrc: "/images/flags/nv.jpg",
    statehoodDate: new Date("1864-10-31"),
  },
  {
    id: "NH",
    name: "New Hampshire",
    capital: "Concord",
    bird: "Purple Finch",
    slogan: "Live Free or Die",
    population: "1,359,711",
    nickname: "The Granite State",
    totalArea: "9,349",
    imageSrc: "/images/flags/nh.svg",
    statehoodDate: new Date("1788-06-21"),
  },
  {
    id: "NJ",
    name: "New Jersey",
    capital: "Trenton",
    bird: "Eastern Goldfinch",
    slogan: "Liberty and Prosperity",
    population: "8,882,190",
    nickname: "The Garden State",
    totalArea: "8,723",
    imageSrc: "/images/flags/nj.jpg",
    statehoodDate: new Date("1787-12-18"),
  },
  {
    id: "NM",
    name: "New Mexico",
    capital: "Santa Fe",
    bird: "Greater Roadrunner",
    slogan: "Crescit Eundo",
    population: "2,096,829",
    nickname: "The Land of Enchantment",
    totalArea: "121,590",
    imageSrc: "/images/flags/nm.svg",
    statehoodDate: new Date("1912-01-06"),
  },
  {
    id: "NY",
    name: "New York",
    capital: "Albany",
    bird: "Eastern Bluebird",
    slogan: "Excelsior",
    population: "19,453,561",
    nickname: "The Empire State",
    totalArea: "54,555",
    imageSrc: "/images/flags/ny.svg",
    statehoodDate: new Date("1788-07-26"),
  },
  {
    id: "NC",
    name: "North Carolina",
    capital: "Raleigh",
    bird: "Northern Cardinal",
    slogan: "Esse quam videri",
    population: "10,488,084",
    nickname: "The Tar Heel State",
    totalArea: "53,819",
    imageSrc: "/images/flags/nc.svg",
    statehoodDate: new Date("1789-11-21"),
  },
  {
    id: "ND",
    name: "North Dakota",
    capital: "Bismarck",
    bird: "Western Meadowlark",
    slogan: "Liberty and Union, Now and Forever, One and Inseparable",
    population: "762,062",
    nickname: "The Peace Garden State",
    totalArea: "70,698",
    imageSrc: "/images/flags/nd.jpg",
    statehoodDate: new Date("1889-11-02"),
  },
  {
    id: "OH",
    name: "Ohio",
    capital: "Columbus",
    bird: "Northern Cardinal",
    slogan: "With God, All Things Are Possible",
    population: "11,689,100",
    nickname: "The Buckeye State",
    totalArea: "44,826",
    imageSrc: "/images/flags/oh.svg",
    statehoodDate: new Date("1803-03-01"),
  },
  {
    id: "OK",
    name: "Oklahoma",
    capital: "Oklahoma City",
    bird: "Scissor-tailed Flycatcher",
    slogan: "Labor Omnia Vincit",
    population: "3,956,971",
    nickname: "The Sooner State",
    totalArea: "69,899",
    imageSrc: "/images/flags/ok.jpg",
    statehoodDate: new Date("1907-11-16"),
  },
  {
    id: "OR",
    name: "Oregon",
    capital: "Salem",
    bird: "Western Meadowlark",
    slogan: "Alis Volat Propriis",
    population: "4,217,737",
    nickname: "The Beaver State",
    totalArea: "98,379",
    imageSrc: "/images/flags/or.svg",
    statehoodDate: new Date("1859-02-14"),
  },
  {
    id: "PA",
    name: "Pennsylvania",
    capital: "Harrisburg",
    bird: "Ruffed Grouse",
    slogan: "Virtue, Liberty, and Independence",
    population: "12,801,989",
    nickname: "The Keystone State",
    totalArea: "46,054",
    imageSrc: "/images/flags/pa.jpg",
    statehoodDate: new Date("1787-12-12"),
  },
  {
    id: "RI",
    name: "Rhode Island",
    capital: "Providence",
    bird: "Rhode Island Red",
    slogan: "Hope",
    population: "1,059,361",
    nickname: "The Ocean State",
    totalArea: "1,545",
    imageSrc: "/images/flags/ri.svg",
    statehoodDate: new Date("1790-05-29"),
  },
  {
    id: "SC",
    name: "South Carolina",
    capital: "Columbia",
    bird: "Carolina Wren",
    slogan: "Dum Spiro Spero",
    population: "5,148,714",
    nickname: "The Palmetto State",
    totalArea: "32,020",
    imageSrc: "/images/flags/sc.svg",
    statehoodDate: new Date("1788-05-23"),
  },
  {
    id: "SD",
    name: "South Dakota",
    capital: "Pierre",
    bird: "Ring-necked Pheasant",
    slogan: "Under God the People Rule",
    population: "884,659",
    nickname: "The Mount Rushmore State",
    totalArea: "77,116",
    imageSrc: "/images/flags/sd.jpg",
    statehoodDate: new Date("1889-11-02"),
  },
  {
    id: "TN",
    name: "Tennessee",
    capital: "Nashville",
    bird: "Northern Mockingbird",
    slogan: "Agriculture and Commerce",
    population: "6,829,174",
    nickname: "The Volunteer State",
    totalArea: "42,144",
    imageSrc: "/images/flags/tn.svg",
    statehoodDate: new Date("1796-06-01"),
  },
  {
    id: "TX",
    name: "Texas",
    capital: "Austin",
    bird: "Northern Mockingbird",
    slogan: "Friendship",
    population: "28,995,881",
    nickname: "The Lone Star State",
    totalArea: "268,596",
    imageSrc: "/images/flags/tx.svg",
    statehoodDate: new Date("1845-12-29"),
  },
  {
    id: "UT",
    name: "Utah",
    capital: "Salt Lake City",
    bird: "California Gull",
    slogan: "Industry",
    population: "3,205,958",
    nickname: "The Beehive State",
    totalArea: "84,897",
    imageSrc: "/images/flags/ut.svg",
    statehoodDate: new Date("1896-01-04"),
  },
  {
    id: "VT",
    name: "Vermont",
    capital: "Montpelier",
    bird: "Hermit Thrush",
    slogan: "Freedom and Unity",
    population: "623,989",
    nickname: "The Green Mountain State",
    totalArea: "9,616",
    imageSrc: "/images/flags/vt.jpg",
    statehoodDate: new Date("1791-03-04"),
  },
  {
    id: "VA",
    name: "Virginia",
    capital: "Richmond",
    bird: "Northern Cardinal",
    slogan: "Sic Semper Tyrannis",
    population: "8,535,519",
    nickname: "The Old Dominion State",
    totalArea: "42,775",
    imageSrc: "/images/flags/va.jpg",
    statehoodDate: new Date("1788-06-25"),
  },
  {
    id: "WA",
    name: "Washington",
    capital: "Olympia",
    bird: "Willow Goldfinch",
    slogan: "Al-ki",
    population: "7,614,893",
    nickname: "The Evergreen State",
    totalArea: "71,298",
    imageSrc: "/images/flags/wa.jpg",
    statehoodDate: new Date("1889-11-11"),
  },
  {
    id: "WV",
    name: "West Virginia",
    capital: "Charleston",
    bird: "Northern Cardinal",
    slogan: "Montani Semper Liberi",
    population: "1,792,147",
    nickname: "The Mountain State",
    totalArea: "24,230",
    imageSrc: "/images/flags/wv.jpg",
    statehoodDate: new Date("1863-06-20"),
  },
  {
    id: "WI",
    name: "Wisconsin",
    capital: "Madison",
    bird: "American Robin",
    slogan: "Forward",
    population: "5,822,434",
    nickname: "The Badger State",
    totalArea: "65,496",
    imageSrc: "/images/flags/wi.jpg",
    statehoodDate: new Date("1848-05-29"),
  },
  {
    id: "WY",
    name: "Wyoming",
    capital: "Cheyenne",
    bird: "Western Meadowlark",
    slogan: "Equal Rights",
    population: "578,759",
    nickname: "The Equality State",
    totalArea: "97,813",
    imageSrc: "/images/flags/wy.svg",
    statehoodDate: new Date("1890-07-10"),
  },
];
